version: '3'

volumes:
  parity: {}
  prometheus: {}
  grafana: {}

services:
  parity:
    image: 'exodusmovement/parity:1.11.8-003'
    container_name: parity
    environment:
      - PARITY_JSONRPC_INTERFACE=all
      - PARITY_ARGUMENTS=--light
    volumes:
      - parity:/home/parity/.local/share/io.parity.ethereum/

  parity-exporter:
    build:
      context: ../
    container_name: parity-exporter
    environment:
      - PARITY_EXPORTER_NODE=http://parity:8545/
    depends_on:
      - parity
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    depends_on:
      - parity-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
