version: '3'

volumes:
  parity: {}
  prometheus: {}
  grafana: {}

services:
  parity:
    image: 'exodusmovement/parity:1.11.8-002'
    container_name: parity
    volumes:
      - parity:/home/parity/.local/share/io.parity.ethereum/
    command: >
      --light
      --jsonrpc-interface all
    ports:
      - 8545:8545

  parity-exporter:
    build:
      context: ../
    container_name: parity-exporter
    depends_on:
      - parity
    volumes:
      - ./parity-exporter/config.yaml:/home/node/parity-exporter/config.yaml
    command: >
      --config config.yaml
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    depends_on:
      - parity-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring
