{
 "title": "Parity",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Sync progress",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoind_blockchain_sync{type=\"progress\"}"
    }
   ]
  },
  {
   "title": "Client version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 13, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "parity_version", "legendFormat": " {{value}}" }
   ]
  },
  {
   "title": "Client chain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 13, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "parity_chain", "legendFormat": "{{value}}" }
   ]
  },
  {
   "title": "Information about latest block",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 5, "y": 6 },
   "targets": [
    { "expr": "parity_latest" }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "parity_peers{version=\"all\"}"
    }
   ]
  },
  {
   "title": "Transactions in mempool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "parity_mempool_size{type=\"size\"}"
    }
   ]
  },
  {
   "title": "Gas price in GWei",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "parity_gas_price / 1000000000" }
   ]
  },
  {
   "title": "Mempool size in KiB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "parity_mempool_size{type=\"bytes\"} / 1024"
    }
   ]
  }
 ]
}